# feeder
feeder: feeders.feeder_uav.Feeder

data_path: ../data/uav/MMVRAC_CSv2.npz
window_size: 64
random_rot: True
use_vel: False
use_angle: False

# model
num_class: 155
num_point: 17
num_person: 2
graph: graph.uav.Graph
k: 1
in_channels: 3
cl_mode: 'ST-Multi-Level'

#optim
weight_decay: 0.0005
base_lr: 0.1
step: [90, 100]
warm_up_epoch: 5

# training
device: 0
batch_size: 128
test_batch_size: 128
num_epoch: 110
nesterov: True

half: True